### ISSUE TITLE
Injecting the theme

### ISSUE THREAD

**Issue by ranbeer2004** [KillYoy/DiscordNight#13]
If we want to inject the theme using developer tools should we create a backup of the css file which we are going to edit?

**Comment by KillYoy** [comment]
There is no need to create a backup, it will only be loaded until the next time Discord restarts. After that the .css reverts back to default. I do not recommend using this method anymore as it totally breaks the theme nowadays. 
Just install BetterDiscord and use that method instead.

**Comment by ranbeer2004** [comment]
Hmm I see thanks 👍
