### ISSUE TITLE
Theme doesnt apply to spotifycontrols plugin

### ISSUE THREAD

**Issue by egg22** [KillYoy/DiscordNight#15]
it would be nice if you could add support for this plugin. otherwise the theme is great
thx :)

![Discord_vAjbHAZ42j](https://user-images.githubusercontent.com/53567996/110140687-40dda500-7dcc-11eb-99b0-0563a9850692.png)

**Comment by KillYoy** [comment]
Hey, I added support for the plugin in the latest version of the theme. If there are any issues in the future or any other plugins you wish were themed feel free to make another issue.
