### ISSUE TITLE
OverExtending Bar

### ISSUE THREAD

**Issue by 23vu1** [KillYoy/DiscordNight#17]
On the latest BandagedBD update for Macos (Beta and Regular), the bar separating the servers from the chats are double as long than they should be. 

*Attached a Picture

<img width="325" alt="image" src="https://user-images.githubusercontent.com/30100414/113657629-f1f18c80-9663-11eb-9345-a0429c163eb7.png">

**Comment by 23vu1** [comment]
Fixable by changing or removing the .base-3dtUhz{left: 64px;} to .base-3dtUhz{left: 0px;} (lines 76-78)

<img width="179" alt="image" src="https://user-images.githubusercontent.com/30100414/113658065-f2d6ee00-9664-11eb-87d3-7a36714801c0.png">

to 

<img width="147" alt="image" src="https://user-images.githubusercontent.com/30100414/113658085-fc605600-9664-11eb-8e71-9421fd621f54.png">

**Comment by KillYoy** [comment]
Just pushed a commit to fix this issue.
