### ISSUE TITLE
Status Icon Projecting Box Inside Profile & Avatars not being Circular.

### ISSUE THREAD

**Issue by Hezron91** [KillYoy/DiscordNight#21]
![Discord_2021-05-27_01-56-30](https://user-images.githubusercontent.com/23535883/119749608-56281400-be8f-11eb-82fc-cc7d12ad99c1.png)

Status icons are projecting it's colour as a box inside profiles when opened.
Also avatars aren't sitting inside the circle container, rather sitting ontop of it.

My versions are here:
![Discord_2021-05-27_02-03-53](https://user-images.githubusercontent.com/23535883/119749831-d6e71000-be8f-11eb-93ad-2032de371387.png)

**Comment by josh-65** [comment]
if you edit the file and remove V in "Online Status Profile Mask" that will make the profile pic image circular.
.userPopout-3XzG_A foreignObject[mask="url(#svg-mask-avatar-status-round-80)"],

**Comment by Hezron91** [comment]
Thanks for the reply but I'm not quite sure what you mean by "remove V" - I'm not that savvy with CSS.

**Comment by josh-65** [comment]
remove the lines below the arrow in the file. most software you can use ctrl+F and paste the line in. then just delete and save it.

**Comment by josh-65** [comment]
Unfortunately i cant find why the activity highlight is not the right space.

**Comment by KillYoy** [comment]
Discord rolled out some big changes yesterday to how the user profile popout is handled, no need to try do any hacky fixes because I will fix this issues and adapt Discords new look soon.

**Comment by Hezron91** [comment]
Thank you KillYoy, I really like your theme great job!

**Comment by josh-65** [comment]
@KillYoy oh right, thought this was always an issue.

**Comment by KillYoy** [comment]
This issue should now be fixed in the latest update.
