### ISSUE TITLE
Avatars are small

### ISSUE THREAD

**Issue by SkylerAlvarez** [KillYoy/DiscordNight#22]
This seems to be happening to every theme, the big avatars when selecting a user on the right side is small and not massive like the picture comparisons in the readme

**Comment by KillYoy** [comment]
This is because Discord recently rolled out some big changes to how the user profile popout is handled and I and other theme developers decided (or their theme is just broken) to adopt this new style Discord is going for. At least for now... So that's why the preview images is outdated atm.

**Comment by SkylerAlvarez** [comment]
Ah understood and unfortunate, I hope that it can be updated in the future but I'm glad it's known, thanks!
