### ISSUE TITLE
User pop outs and full profiles are in discords default style

### ISSUE THREAD

**Issue by josh-65** [KillYoy/DiscordNight#24]
**Screenshots:**
![image](https://user-images.githubusercontent.com/26977075/122658305-792ea680-d163-11eb-9be5-9cc472791299.png)
![image](https://user-images.githubusercontent.com/26977075/122658307-80ee4b00-d163-11eb-8f98-73dfd4989069.png)

**Versions:**
![image](https://user-images.githubusercontent.com/26977075/122658317-98c5cf00-d163-11eb-9477-4b58805e9a80.png)

**Comment by KillYoy** [comment]
This issue has now been resolved in the newest update to the theme.
