### ISSUE TITLE
DiscordNight doesn't allow the shortcuts menu to scroll

### ISSUE THREAD

**Issue by tynansdtm** [KillYoy/DiscordNight#27]
With DiscordNight and no other plugins, you can't scroll the shortcut menu (Ctrl-/) with the mouse wheel and you can't click where the short cut bar should be.

**Comment by KillYoy** [comment]
Thanks for the notice, I will be fixing this soon.

**Comment by KillYoy** [comment]
This issue has now been resolved in the newest update to the theme.
