### ISSUE TITLE
All icons in settings are globe ones

### ISSUE THREAD

**Issue by josh-65** [KillYoy/DiscordNight#31]
![image](https://user-images.githubusercontent.com/26977075/131263301-372a8cc5-1758-4797-b100-77b922472d7f.png)

**Comment by brawas** [comment]
Same here! Using ```version 0.9.4```

**Comment by josh-65** [comment]
Can be fixed by adding copying the content from the imported URL in the file and then this to the top of the file
@import url("https://mwittrien.github.io/BetterDiscordAddons/Themes/_res/SettingsIcons.css");

and removing from the file
.standardSidebarView-3F1I7i .side-8zPYf6 [aria-controls*="-tab"]::before {
	background: url("https://raw.githubusercontent.com/KillYoy/DiscordNight/master/Icons/SVG/Language.svg");
}

**Comment by KillYoy** [comment]
Discord felt like changing the names from all caps to lowercase for some reason. Now if in the future they ever feel like doing that again, now the code is no longer case sensitive.
