### ISSUE TITLE
Minor CSS issue prolly

### ISSUE THREAD

**Issue by r3tr0-02** [KillYoy/DiscordNight#33]
![image](https://user-images.githubusercontent.com/91692409/140635622-c60ff31a-a16c-4a25-8f39-c11ca6d6fb0d.png)

Just opened discord and saw this eyesore lul ; happens when the member's list is in small amount

**Comment by r3tr0-02** [comment]
![image](https://user-images.githubusercontent.com/91692409/140635744-3f80ac1d-c128-4f60-8b9c-097876a980ea.png)


can be fixed with inspect -> search the member list's container -> disable the background or change the colour 

- note this fix will stay until restart

**Comment by KillYoy** [comment]
Discord likes doing these random pointless changes, sorry for the delayed fix.
