### ISSUE TITLE
Highlight for speaking user in channel list gets square and weird

### ISSUE THREAD

**Issue by nearcatch** [KillYoy/DiscordNight#34]
![image](https://user-images.githubusercontent.com/692914/142043527-08d9aca7-57f4-463a-9276-dcf06003f0a6.png)
![image](https://user-images.githubusercontent.com/692914/142043593-4ad4ef80-55f7-47c0-8ede-b6b13709e9ef.png)

Highlight for speaking user in channel list gets odd when DiscordNight is activated. Happens in default and when names are hidden.

**Comment by KillYoy** [comment]
Forgot to add code to check if the category was collapsed or not when users are speaking, should be fixed now.
