### ISSUE TITLE
issue with background

### ISSUE THREAD

**Issue by qwerty8866** [KillYoy/DiscordNight#37]
hey, I'm having some issues with the background that involve a "merge" between discordnight and normal discord 
![Screenshot 2022-01-10 155019](https://user-images.githubusercontent.com/97485179/148857250-7c426dcb-e027-453b-aae3-771d31e5411c.jpg)
not sure if its just me or a common issue, really like your work tho so it'd be great if there was a fix

**Comment by KillYoy** [comment]
Discord just pushed out an update that breaks the majority of all BetterDiscord themes so you have them to thank for it. 
I did know this was coming as on both PTB and Canary the theme has been broken for a couple of days so I had some time to prepare for it, I will be fixing this issue soon.

**Comment by SpaceN64** [comment]
thanks

**Comment by qwerty8866** [comment]
ok sweet, thanks man
