### ISSUE TITLE
Default Discord Image Not Displaying For Users In Channels

### ISSUE THREAD

**Issue by christiangrothaus** [KillYoy/DiscordNight#38]
![04-24-2022_13 46 30_Discord](https://user-images.githubusercontent.com/18076531/164989502-aabb8736-8a83-4687-a015-7dd981e1ae82.png)
From the picture you can see that "DigiBlak" does not have a profile image displayed in the user list for the channels but in the server list he has a default profile image.  I have no other themes enabled and haven't changed any CSS.  I also fresh installed the theme yesterday.

**Comment by KillYoy** [comment]
I fail to see how this issue is related to the theme and is not caused by anything else like plugins or just Discord bugging out.

**Comment by christiangrothaus** [comment]
> I fail to see how this issue is related to the theme and is not caused by anything else like plugins or just Discord bugging out.

Only happens with this theme and there is no plugins installed.

![image](https://user-images.githubusercontent.com/18076531/164990697-93fdc1a4-6630-4ee9-910b-30bad2fe198c.png)

![image](https://user-images.githubusercontent.com/18076531/164990712-cdeca7be-dbfd-476e-ab0d-bf6305bf03b9.png)

**Comment by KillYoy** [comment]
Alright, I see the issue now. I will push a fix for it soon.
