### ISSUE TITLE
Discord Update (Status Menu)

### ISSUE THREAD

**Issue by thiaguinho4** [KillYoy/DiscordNight#42]
after the update, the status menu changed and the microphone & configuration buttons moved a little to the left corner (one question, could you make an addon to go back to the old status menu?) Thanks <3

![1](https://user-images.githubusercontent.com/101910294/183217361-dc75f607-758e-4fd2-8823-767f7d0af7e8.png)

**Comment by KillYoy** [comment]
Buttons position is easily fixable but making the new menu look like it did before is probably not possible using only CSS since the old status menu is now placed in a submenu instead.
