### ISSUE TITLE
Typing in the new suggestions forums causes the width of the player list to shrink

### ISSUE THREAD

**Issue by Katakalysm** [KillYoy/DiscordNight#48]
This is a weird bug, it's hard to notice till you start writing massive paragraphs in there and then it becomes hard to unnotice.
It's not very important but still figured I'd report it.
![image](https://user-images.githubusercontent.com/105556520/206379049-8f2bf8a3-9828-4342-865b-c2bdadbce885.png)
This is how it looks with an empty chat box.

Then without an empty chatbox it looks like this:
![image](https://user-images.githubusercontent.com/105556520/206379426-6e097200-d1c4-44ea-8581-f4e265b7ccec.png)

Why I think this is a bug and not a feature is because it doesn't happen in any other channel:
![image](https://user-images.githubusercontent.com/105556520/206379700-3f3db803-8e6e-4856-90d3-baa2ad302ff7.png)

**Comment by KillYoy** [comment]
A very Discord thing to have things look the same but behave different thus causing issue, it's now resolved anyway.
