### ISSUE TITLE
Friends are spaced out in friends list

### ISSUE THREAD

**Issue by pairofsock** [KillYoy/DiscordNight#49]
It gets quite annoying
![image](https://user-images.githubusercontent.com/126544102/225778540-5ef2ae7e-98cb-4ea0-a88a-1091d0017c63.png)

**Comment by pairofsock** [comment]
The more people in the specific list the more spaced out it gets
![image](https://user-images.githubusercontent.com/126544102/225778736-e4236740-243b-46d1-922f-a010e93104b2.png)
![image](https://user-images.githubusercontent.com/126544102/225778791-319b0d43-6bbe-46c7-93f2-28cdff916dae.png)

**Comment by Hinatahyugahime** [comment]
same issue here

**Comment by KillYoy** [comment]
Issue should now be fixed in themes latest update
