### ISSUE TITLE
Discord Settings Icon order

### ISSUE THREAD

**Issue by DarkoJB** [KillYoy/DiscordNight#53]
Not a functionality-breaking bug, but the order of the icons in App Settings section of Discord's settings is not correct.

![image](https://github.com/KillYoy/DiscordNight/assets/75065962/df6afdf8-ee7b-4e72-b1df-7f3d9f4295d0)

**Comment by KillYoy** [comment]
Though the settings icons order should be better now it will not always be perfect with how Discord has set up the settings pages. It is not possible to set a specific icon for each one currently and instead revolves around the pages order. So when they add a new one the icons below the new one will show the wrong icon.
