### ISSUE TITLE
Noise suppression icon missing

### ISSUE THREAD

**Issue by Shade123ITA** [KillYoy/DiscordNight#55]
Recently I started using this theme since I find it very nice for many things, but it's been since I started using this theme that the noise suppression icon has disappeared from Discord whenever I join voice calls in servers or DMs. Is there any fix for this that I could try? It's driving me crazy going to the settings everytimes to check if I have noise suppression and/or test my mic.

![before](https://github.com/KillYoy/DiscordNight/assets/78645478/6e709f4f-31f1-4f03-ad3b-c63e35b6f36f) Before adding the theme
![after](https://github.com/KillYoy/DiscordNight/assets/78645478/0744304e-2200-497e-9d91-18bd486b0531) After adding the theme

**Comment by KillYoy** [comment]
Read the section "Customizing the theme" in the description/readme on how to enable the button again using the "--Voice-Noise-Suppression" variable
