### ISSUE TITLE
Settings icon gone? how to get back?

### ISSUE THREAD

**Issue by DomezTheDragon** [KillYoy/DiscordNight#57]
![image](https://github.com/KillYoy/DiscordNight/assets/142619057/926af90a-a85a-484b-b6e9-813cd4b5355e)
![image](https://github.com/KillYoy/DiscordNight/assets/142619057/639dc736-9fb2-46e4-948c-9ad0f7d1eb99)
it's only with this theme, unless it's a setting, it's a bug in my eyes

**Comment by OGPanzerhund** [comment]
Recent discord update fucked up the icons. Just use discord without the theme for now.

**Comment by KillYoy** [comment]
A Discord update messed them up it's now fixed in the recent theme update
