### ISSUE TITLE
Several issues regarding icons

### ISSUE THREAD

**Issue by OGPanzerhund** [KillYoy/DiscordNight#58]
- Mute, deafen and settings icons not condensed to be smaller (ignore the game controller icon, that's from another betterdiscord plugin)
- chat box's gif, media, emoji, etc icons appearing again, rather than being condensed to just the emoji icon
- upload a file icon moved back to the left side
basically, icons and buttons are not showing like they should. 

![image_2023-10-17_004949348](https://github.com/KillYoy/DiscordNight/assets/33360827/b74cd60a-7ba4-43ef-8745-9155966b9948)
![image_2023-10-17_005106087](https://github.com/KillYoy/DiscordNight/assets/33360827/bc2e7ba0-d875-4032-8c65-3628db37911e)

**Comment by KillYoy** [comment]
Fixed in the recent theme update
