### ISSUE TITLE
new discord css update, theme broke again

### ISSUE THREAD

**Issue by Oxxi1337** [KillYoy/DiscordNight#63]
title

**Comment by Norway174** [comment]
Can confirm. Same here.
Hoping for a fix soon. This theme is just so good!

**Comment by KillYoy** [comment]
Everything should be back to normal now in the latest update

**Comment by TheLovinator1** [comment]
> Everything should be back to normal now in the latest update

Thanks KillRoy, I donated 756 Japanese Yen via [GitHub Sponsors](https://github.com/sponsors/KillYoy)™️ so you can buy Pepsi Cola 🧃
